merchantos/PrintTemplates

receipt/SaleReceipt.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

Fix the subtotal amount to be the tax amount and not the sale amount.

CLD-9340:  Sale receipts display taxed subtotals incorrectly

---

receipt/SaleReceipt.tpl

Adds support for displaying triPOS payments in the sale receipt (english only).
_Author's Note_: This is a port of the changes to the SaleReceipt.tpl template in the webPOS repository.

CLD-15479: Update english sale receipt template for triPOS

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

The changeset brings the print templates in line with the latest changes for Retail.  It includes:
+ Generic support to detect when a signature is required
+ Specific support for triPOS receipts

CLD-16592: Updated signature capture method

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

The Twig templates used for receipts compare a SimpleXmlElement
to `true`. Sometimes the SimpleXmlElement is empty.
On PHP 5.6 Twig evaluates this empty element to `false` but on
PHP 7.2 it evaluates it to `true`.
This change adds the `CompBool` filter to these comparisons.
This is a copy of https://github.com/merchantos/webPOS/pull/10953

CLD-18928 Receipt line is always printed with PHP 7

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

This reverts commit c797310038b0b6c4aa29e63a6ec6f0a4228cf9cb.
Since the PHP7 update has been rolled back, this needs to be
reverted too.

Revert "CLD-18928 Receipt line is always printed with PHP 7"

---

.gitignore
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_fr_CH.tpl

- All sales are tax-inclusive
- Tax level in (%)
- Amount of tax, excluding tax (sub-total) and total
- Support Tax Levels : When multiple taxes are recorded during a sale, a letter can be displayed to differentiate the tax type. That needs to be summed and displayed on the bottom of the ticket
- Name of business, postal code, city, ISO tax code
- Support localization/translations: FR: TVA, DE: MwST, IT: IVA
- Discounts are made price that includes the VAT
- Include VAT Number in footer and confirm VAT is included

CLD-26475: Add fiscal compliant invoices for Switzerland

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

- FIX internal notes display when the print_layout is true
- Added words Montant payé en espèces and Contant betaald bedrag respectively for amount paid in cash
- Added conditional checking whether the sale was completed and the quoteID was gt 1 to remove rounded total

CLD-28090 templates updates: Internal notes display and Belgium rounding

---

workorder/default.tpl

Added the internal notes secction on a work order
tag.

[CLD-28966] Added workorder internal notes to tag

---

workorder/customizable_workorder.tpl

Added internal notes section to custom work order template:

[CLD-31719] Add internal notes on custom workorder template

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_fr_CA-QC.tpl

Condition to print payment fields now checks for empty strings as well.
Applied missing updates to the template.
Removed duplicated macro declaration.

Hide empty payment fields on sale receipt

---

purchase_order/purchase_order.tpl

New metadata fields introduced for the Order DisplayTemplate
This is the pull request for updating the Retail API docs https://github.com/lightspeedretail/lightspeedretail.github.io/pull/356

Update purchase order receipt template metadata fields

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

Sync minor updates from previous work:
- Remove 40px margin-bottom on `.store`
- Wrap barcode in `p.barcodeContainer`
- Replace `th` with `td`
- Remove duplicated macro declaration
- Harden "exist" validation strategy with `strlen` for `if` statements
- Hide empty payment fields
New capability:
- Display tip value when applicable.

LSR-3339 Sync Template Updates

---

purchase_order/purchase_order.tpl

This will allow customers with multi-currency to see the respective vendor currency symbol in the PO template.  This is made possible with the addition of a custom twig filter "format_currency". Latest version of twig already implements this filter but we are still on an older version of twig at the moment
PR with the new filter https://github.com/merchantos/webPOS/pull/16764

Add filter to accommodate multi-currency symbol

---

purchase_order/purchase_order.tpl

Previously, the first vendor ID in the list would be chosen, now the vendor ID that matches the PO vendor will print, else the field will be blank.

LSR-13378: Custom Template for Purchase Order is not displaying the correct Vendor ID

---

workorder/customizable_workorder.tpl
workorder/customizable_workorder_QC.tpl
workorder/default.tpl

Previously when a customer's address was not filled in, or not full information there could be a trailing comma in this section.

LSR-13879: Fix workorder template address section

---

label/customizable_label.tpl

Previously, when a user changed "price_with_no_cents" to true, the label template had hard coded "$" as the currency symbol

LSR-167: Print Label without cents doesn't respect the currency of your account

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

The error I was getting was that even if show_shop_name_with_logo was set to true, it wouldn't show as the macros seem to have their own scope. Adjustment is `options.show_shop_name_with_logo`

LSR-13687: Print templates - show_shop_name_with_logo = false doesn't remove shop name from custom SaleReceipt

---

workorder/customizable_workorder.tpl
workorder/customizable_workorder_QC.tpl

See explanations and screenshots on [LSR-5340](https://jira.atlightspeed.net/browse/LSR-5340)

LSR-5340: Work Orders show Price excluding Taxes on the receipt in Tax Inclusive environment when the template is ON

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

Port over all updates from Retail for the updated Sale Receipt templates (to include cc info)

LSR-13999: Card info do not show on localized receipts

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

Displayable unit price vs unit price:
displayableUnitPrice | (float) Reflect the current unit price that the customer is charged for after price rule and only price rule percent discount (not fixed).
-- | --
unitPrice | (float) the unit price. May be adjusted by price rules. Can be negative for rebates or other uses, but not for refunds. Refunds are handled through negative unitQuantity
-- | --

LSR-14158: Incorrect strike out price when an item is discounted from a Price Rule.

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

The issue was that if the option was `true` it would add the header but for the row it would check if there was data to add first. The row `<td/>` needs to be added if the header is added else the table will not be balanced. 
<table>
<tr>
<td>
<h3>Before</h3>
</td>
<td>
<h3>After</h3>
</td>
</tr>
</table>

LSR-5345: Fix receipt alignment issue when using sku column

---

label/customizable_label.tpl

Prior to this change only the first label would get the correct margin adjustments from the configuration and the subsequent ones would not get it.
<table>
<tr>
<td>
<h3>Before</h3>
</td>
<td>
<h3>After</h3>
</td>
</tr>
</table>

LSR-9362: Fix margin not respected on label batch

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

With change (first screenshot is `show_customer_name_only` set to false, second screenshot is set to true)

LSR-18136: show_customer_name_only option in receipt template does not hide company name

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

Instead of being columns where text may overflow and the price being pushed out of the printable area, have the `manufacturer sku` and `custom sku` show below the item description.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

LSR-6698: Fix receipt CustomSKU and ManufacturerSKU columns

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

The `subtotal` amount for `taxInclusive` accounts was inaccurate. This PR fixes that.
**WebPOS PR:** https://github.com/merchantos/webPOS/pull/21670
**Before Fix**
**After Fix**

LSR-22416: Show accurate subtotal for taxInclusive accounts 

---

receipt/SaleReceipt.tpl
receipt/SaleReceipt_de_CH.tpl
receipt/SaleReceipt_es.tpl
receipt/SaleReceipt_fr_BE.tpl
receipt/SaleReceipt_fr_CA-QC.tpl
receipt/SaleReceipt_fr_CH.tpl
receipt/SaleReceipt_nl_BE.tpl
receipt/SaleReceipt_nl_NL.tpl

This is just a reflection update to update our public facing repo with the translations that were done prior

LSR-28559 - Translate Sale Receipt Templates to Supported Languages
